spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_traffic
    username: root
    password: 123456

server:
  port: 8088
  servlet:
    context-path: /



mybatis:
  configuration:
    map-underscore-to-camel-case: true
